name: larva
description: Larva is a multicultural offline avatar maker. 12 billion unique multicultural avatars
homepage: https://github.com/rey-xi
version: 0.0.1+8

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.2
  flutter_svg: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
